FROM node:20-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .

ARG NEXT_PUBLIC_RECAPTCHA_SITE_KEY
ARG RECAPTCHA_SECRET_KEY
ARG GMAIL_USER
ARG GMAIL_APP_PASSWORD

ENV NEXT_PUBLIC_RECAPTCHA_SITE_KEY=$NEXT_PUBLIC_RECAPTCHA_SITE_KEY
ENV RECAPTCHA_SECRET_KEY=$RECAPTCHA_SECRET_KEY
ENV GMAIL_USER=$GMAIL_USER
ENV GMAIL_APP_PASSWORD=$GMAIL_APP_PASSWORD

RUN npm run build
EXPOSE 3000
CMD ["npm", "run", "start"]